spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: TODO_LIST
    password: 1911
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret: todo-list-jwt-secret-key-with-32-chars-minimum
      expiration-minutes: 15
      refresh-expiration-days: 7
      max-sessions: 1
    cleanup:
      cron: "0 0 * * * *"
