/*
OBJETIVO
- Criar a tabela de relacionamento PAPEL_PERMISSAO.
- Definir quais permissões são válidas para cada papel (Matriz de Permissões).
*/

DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM ALL_TABLES
     WHERE OWNER = 'TODO_LIST'
       AND TABLE_NAME = 'PAPEL_PERMISSAO';

    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE TODO_LIST.PAPEL_PERMISSAO (
                PAPEL_ID NUMBER NOT NULL,
                PERMISSAO_ID NUMBER NOT NULL,
                CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT PK_PAPEL_PERMISSAO PRIMARY KEY (PAPEL_ID, PERMISSAO_ID),
                CONSTRAINT FK_PP_PAPEL FOREIGN KEY (PAPEL_ID) REFERENCES TODO_LIST.PAPEL (ID),
                CONSTRAINT FK_PP_PERMISSAO FOREIGN KEY (PERMISSAO_ID) REFERENCES TODO_LIST.PERMISSAO (ID)
            )
        ]';
    END IF;
END;
/

-- Populando a Matriz de Permissões
-- USUARIO: VISUALIZAR, CRIAR, EDITAR, BLOQUEAR
-- TAREFA_CATEGORIA: VISUALIZAR, CRIAR, EDITAR, BLOQUEAR
-- TAREFA: VISUALIZAR, CRIAR, EDITAR, BLOQUEAR

INSERT INTO TODO_LIST.PAPEL_PERMISSAO (PAPEL_ID, PERMISSAO_ID)
SELECT PA.ID, PE.ID
FROM TODO_LIST.PAPEL PA, TODO_LIST.PERMISSAO PE
WHERE NOT EXISTS (
    SELECT 1 FROM TODO_LIST.PAPEL_PERMISSAO PP 
    WHERE PP.PAPEL_ID = PA.ID AND PP.PERMISSAO_ID = PE.ID
);

COMMIT;
