CREATE OR REPLACE VIEW VW_TAREFA_ANALITICO AS
SELECT
    T.ID AS TAREFA_ID,
    T.USUARIO_ID,

    T.STATUS_ID,
    S.CODIGO AS STATUS_CODIGO,
    S.DESCRICAO AS STATUS_DESCRICAO,

    T.PRIORIDADE_ID,
    P.CODIGO AS PRIORIDADE_CODIGO,
    P.DESCRICAO AS PRIORIDADE_DESCRICAO,

    T.CATEGORIA_ID,
    C.NOME AS CATEGORIA_NOME,

    T.ATIVO,
    T.DATA_FIM,
    T.DATA_CONCLUSAO,
    T.CREATED_AT
FROM TAREFA T
         INNER JOIN TAREFA_STATUS S ON S.ID = T.STATUS_ID
         INNER JOIN TAREFA_PRIORIDADE P ON P.ID = T.PRIORIDADE_ID
         LEFT JOIN TAREFA_CATEGORIA C ON C.ID = T.CATEGORIA_ID;