export const ROLES = {
  TASK_VIEW: 'TAREFA_VISUALIZAR',
  TASK_CATEGORY_VIEW: 'TAREFA_CATEGORIA_VISUALIZAR',
  TASK_INDICATORS_VIEW: 'INDICADORES_TAREFAS_VISUALIZAR',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];
